### ISSUE TITLE
[4H] Draft a design for the results page

### ISSUE THREAD

**Issue by RemiBardon** [chocoteam/PerformanceAction#2]
TODO:

- [x] Decide how to organize the page → ([see answer](https://github.com/chocoteam/PerformanceAction/issues/2#issuecomment-848665123))
- [x] Decide how to handle a change from `0` to a value (% would be infinite) → No percentage ([see answer](https://github.com/chocoteam/PerformanceAction/issues/2#issuecomment-855746496))
- [x] Decide how to handle a change from nothing to a value → Handle it as an `=` ([see answer](https://github.com/chocoteam/PerformanceAction/issues/2#issuecomment-855747540))
- [x] Decide whether to show numeric difference (`+1`, `-3`), percentages (`+7%`, `-2%`) or both → both ([see answer](https://github.com/chocoteam/PerformanceAction/issues/2#issuecomment-851610654))

**Comment by RemiBardon** [comment]
I'm drafting a design, and I thought about something: it would be good to have an HTML heading tag (`h1`, `h2`, `h3`…) for each log line, as Hugo would auto-generate an `id` for each input file. it would allow one to click on the name of an input file, and after refreshing the page, still being at the same place (not having to search for the file again).

As you can see on this screenshot, hovering the `h4` shows a 🔗 icon next to it.

<img width="506" alt="Screenshot 2021-05-26 at 12 10 19" src="https://user-images.githubusercontent.com/37386490/119642811-68686a80-be1b-11eb-9d2f-6fd1ffeaf7b5.png">

Side note: if multiple input files have the same name but different paths (represented by the headings structure – h1>h2>h3 <=> `/h1/h2/h3` file), HTML `id`s would conflict. Hugo [automatically generated a unique postfixed `id`](https://gohugo.io/content-management/cross-references/#heading-ids), so it's not a problem.

**Comment by RemiBardon** [comment]
For `/home/evaluation/evaluation/pub/bench/XCSP18/CrosswordDesign/CrosswordDesign-03-4-rom_c18` as an input file, for example, I think it's good to have:

- Article title as `h1`
- `XCSP18` as `h2`
- `CrosswordDesign` as `h3`
- `CrosswordDesign-03-4-rom_c18` as `h4`

This allows:

- A useful Table Of Contents with no clutter (only `h2`s and `h3`s are listed)
- The ability to link a specific file (`h4` `id` attribute)

**Comment by RemiBardon** [comment]
@cprudhom In the benchmarks page, what do you want to compare? Is it the last value (JSON object) of the logged JSON array or do you need all/some of the values?

For example (with dummy data):

<img width="803" alt="Screenshot 2021-05-26 at 12 46 34" src="https://user-images.githubusercontent.com/37386490/119647318-6b198e80-be20-11eb-9b8e-57e4565298e1.png">

Is this okay or do you need more data (the first value, the middle one, all of them)?

**Comment by cprudhom** [comment]
I don't where the reference value comes from. Is it the previous value (from previous commit), an average value on the _n_ last commits? Or something else?

**Comment by FlorianDussable** [comment]
I'd say the reference value for regression detection would be taken from the previous commit.
But it could also be interesting to establish a trend based on the n last commits.

**Comment by RemiBardon** [comment]
Note: Need to decide how to handle a change from `0` to `1` for example.

**Comment by RemiBardon** [comment]
> I don't where the reference value comes from. Is it the previous value (from previous commit), an average value on the n last commits? Or something else?

The page says

> Results are compared with [`13a4c1d`](https://github.com/chocoteam/choco-solver/commit/13a4c1dca0dd58d62acc741866fb945f3fe81592).

For now, it compares one commit with another (#9). It can be the last commit or a specific one, set in GitHub Action configuration. In sprint 2, we will handle comparison between 1 commit and n others (#15).

**Comment by RemiBardon** [comment]
**Note to self:**

In <https://github.com/chocoteam/PerformanceAction/issues/2#issuecomment-848665123>, I implied there would only be `h1`s, `h2`s, `h3`s and `h4`s.

I was wrong, an example shows a `h5` could be present:

```out
/XCSP18/Rlfap/Rlfap-opt/Rlfap-scen-03-opt_c18
/XCSP18/Rlfap/Rlfap-opt/Rlfap-scen-06-opt_c18
```

We won't make assumptions considering the depth of file paths.

**Comment by RemiBardon** [comment]
> Decide whether to show numeric difference (`+1`, `-3`), percentages (`+7%`, `-2%`) or both

I think it's better to have both. I checked the box.

**Comment by RemiBardon** [comment]
> Decide how to handle a change from `0` to a value (% would be infinite)

I think the easy way is not to show any percentage. It can be passed to the program as a variation in value with a `0` percent variation.

**Comment by RemiBardon** [comment]
> Decide how to handle a change from nothing to a value

Variation does not make sense, so it should be `0` in value and `0` in percentage.
